### ISSUE TITLE
Amount class gets NullException

### ISSUE THREAD

**Issue by dirkarnez** [dmitry-merzlyakov/nledger#23]
![image](https://user-images.githubusercontent.com/26408605/149435895-42fc0002-14eb-4e43-a10b-f94125e5edb3.png)

I tried this piece of testing code in .net core 3 and .net framework 4.7, both show the same exception. Thank you!

**Comment by dmitry-merzlyakov** [comment]
Hi, please check this documentation: https://github.com/dmitry-merzlyakov/nledger/blob/next-dev/build.md

In few words: if you are going to use a Standalone session (so, use NLedger DOM directly in your code), you should organize a scope for it (CreateStandaloneSession):

using(var session = NetSession.CreateStandaloneSession())
{
    var eur = CommodityPool.Current.FindOrCreate("EUR");
    var totalEur = new Amount("0.00 EUR");

Thanks,
Dmitry

**Comment by dirkarnez** [comment]
I see, I missed this documentation. Thank you @dmitry-merzlyakov !
