### ISSUE TITLE
Tags are duplicated when printing

### ISSUE THREAD

**Issue by aaubry** [dmitry-merzlyakov/nledger#24]
Parsing a file with tags and printing it causes the tags to be duplicated. For example, the command `NLedger-cli.exe -f test.ledger print` where `test.ledger` contains this:
```
2022/01/30 * stuff  ;Misc
    ; UUID: 0292006581600/20220130/0
    Expenses:Unknown                         123 €
    Assets:Wallet
```
produces the following output:
```
2022/01/30 * stuff
    ;Misc
    ; UUID: 0292006581600/20220130/0
    ; UUID: 0292006581600/20220130/0
    Expenses:Unknown                           123 €
    Assets:Wallet
```

The original ledger application produces the correct output:
```
2022/01/30 * stuff
    ;Misc
    ; UUID: 0292006581600/20220130/0
    Expenses:Unknown                           123 €
    Assets:Wallet
```

**Comment by dmitry-merzlyakov** [comment]
Hi @aaubry, thank you for letting me know. I will take a look at it in a couple of days and update this ticket, thanks
