### ISSUE TITLE
just question

### ISSUE THREAD

**Issue by cysnet** [dmitry-merzlyakov/nledger#4]
how can i start the project NLedge.CLI

**Comment by cysnet** [comment]
when i run the project NLeder.CLI,i got an error message:
No journal file was specified (please use -f)

**Comment by dmitry-merzlyakov** [comment]
This is a command line utility, so you should specify proper command line parameters to run it. For example, you may specify something like **NLedger-cli.exe bal -f drewr.dat** assuming you want to get a balance using the file drewr.dat.
I highly recommend reviewing Ledger documentation (you can find it in the file \Contrib\ledger3.html); the number of parameters is really big.

**Comment by cysnet** [comment]
> This is a command line utility, so you should specify proper command line parameters to run it. For example, you may specify something like **NLedger-cli.exe bal -f drewr.dat** assuming you want to get a balance using the file drewr.dat.
> I highly recommend reviewing Ledger documentation (you can find it in the file \Contrib\ledger3.html); the number of parameters is really big.

thanks ,i will read the html file

**Comment by cysnet** [comment]
> This is a command line utility, so you should specify proper command line parameters to run it. For example, you may specify something like **NLedger-cli.exe bal -f drewr.dat** assuming you want to get a balance using the file drewr.dat.
> I highly recommend reviewing Ledger documentation (you can find it in the file \Contrib\ledger3.html); the number of parameters is really big.

Can this tool add data to dat file?

**Comment by dmitry-merzlyakov** [comment]
No, the primary concept of this tool is to read a specially formatted text file and provide a big variety of output reports.

**Comment by cysnet** [comment]
> No, the primary concept of this tool is to read a specially formatted text file and provide a big variety of output reports.

ok,I will learn how to use this tool.

**Comment by alensiljak** [comment]
@cysnet, please have a look at the Ledger docs at 

https://ledger-cli.org/doc/ledger3.html

This project is an implementation of the same logic using dotnet platform. So, all the same rules apply.

That said, this issue can probably be closed as complete. :)
